name: CI

on:
  push:
    branches: [ main, '*' ]
  pull_request:
    branches: [ main, '*' ]

permissions:
  contents: read
  checks: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build & Test (stable)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Show rustc version
        run: rustc -Vv

      - name: Build (all targets)
        run: cargo build --workspace --all-targets --all-features --locked

      - name: Run tests
        run: cargo test --workspace --all-features --locked --no-fail-fast

      - name: Doc build (no deploy)
        run: cargo doc --workspace --no-deps --locked

  lint:
    name: Format & Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Rust toolchain (clippy, rustfmt)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-features -- -D warnings

  minimal:
    name: Minimal features compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - uses: dtolnay/rust-toolchain@stable
      - name: Build default feature set
        run: cargo build --workspace --locked
